-- Q1. What is the total revenue generated by male vs. female customers?
SELECT Gender, SUM(`Purchase Amount (USD)`) AS total_revenue
FROM shopping_behavior
GROUP BY Gender;


-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT `Customer ID`, `Item Purchased`, `Purchase Amount (USD)`, `Discount Applied`
FROM shopping_behavior
WHERE `Discount Applied` = 'Yes'
  AND `Purchase Amount (USD)` > (SELECT AVG(`Purchase Amount (USD)`) FROM shopping_behavior)
ORDER BY `Purchase Amount (USD)` DESC;

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT `Item Purchased` AS product,
       ROUND(AVG(`Review Rating`), 2) AS avg_review_rating
FROM shopping_behavior
GROUP BY `Item Purchased`
ORDER BY avg_review_rating DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
SELECT `Shipping Type`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase_amount
FROM shopping_behavior
WHERE `Shipping Type` IN ('Standard', 'Express')
GROUP BY `Shipping Type`;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue.
SELECT `Subscription Status`,
       ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_spend,
       SUM(`Purchase Amount (USD)`) AS total_revenue
FROM shopping_behavior
GROUP BY `Subscription Status`;

-- Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT `Item Purchased` AS product,
       COUNT(*) AS total_purchases,
       SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) AS discounted_purchases,
       ROUND(100.0 * SUM(CASE WHEN `Discount Applied` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2)
           AS discount_percentage
FROM shopping_behavior
GROUP BY `Item Purchased`
ORDER BY discount_percentage DESC
LIMIT 5;


-- Q7. Segment customers into New, Returning, and Loyal based on previous purchases.
-- New = 0-1, Returning = 2-5, Loyal = more than 5
SELECT
    CASE
        WHEN `Previous Purchases` <= 1 THEN 'New'
        WHEN `Previous Purchases` BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count,
    ROUND(AVG(`Purchase Amount (USD)`), 2) AS avg_purchase_amount,
    SUM(`Purchase Amount (USD)`) AS total_revenue
FROM shopping_behavior
GROUP BY
    CASE
        WHEN `Previous Purchases` <= 1 THEN 'New'
        WHEN `Previous Purchases` BETWEEN 2 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END
ORDER BY customer_count DESC;


-- Q8. What are the top 3 most purchased products within each category?
WITH product_sales AS (
    SELECT Category,
           `Item Purchased` AS product,
           COUNT(*) AS purchase_count,
           ROW_NUMBER() OVER (
               PARTITION BY Category
               ORDER BY COUNT(*) DESC
           ) AS product_rank
    FROM shopping_behavior
    GROUP BY Category, `Item Purchased`
)
SELECT Category, product, purchase_count, product_rank
FROM product_sales
WHERE product_rank <= 3
ORDER BY Category, product_rank;


-- Q9. Are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT
    CASE WHEN `Previous Purchases` > 5 THEN 'Repeat Buyer'
         ELSE 'Non-Repeat Buyer' END AS customer_type,
    COUNT(*) AS total_customers,
    SUM(CASE WHEN `Subscription Status` = 'Yes' THEN 1 ELSE 0 END) AS subscribed_customers,
    ROUND(100.0 * SUM(CASE WHEN `Subscription Status` = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2)
        AS subscription_rate
FROM shopping_behavior
GROUP BY CASE WHEN `Previous Purchases` > 5 THEN 'Repeat Buyer'
             ELSE 'Non-Repeat Buyer' END;




-- Q10. What is the revenue contribution of each age group?
-- Age groups: 18-25, 26-35, 36-45, 46-55, 56+
WITH age_revenue AS (
    SELECT
        CASE
            WHEN Age BETWEEN 18 AND 25 THEN '18-25'
            WHEN Age BETWEEN 26 AND 35 THEN '26-35'
            WHEN Age BETWEEN 36 AND 45 THEN '36-45'
            WHEN Age BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END AS age_group,
        SUM(`Purchase Amount (USD)`) AS revenue
    FROM shopping_behavior
    GROUP BY
        CASE
            WHEN Age BETWEEN 18 AND 25 THEN '18-25'
            WHEN Age BETWEEN 26 AND 35 THEN '26-35'
            WHEN Age BETWEEN 36 AND 45 THEN '36-45'
            WHEN Age BETWEEN 46 AND 55 THEN '46-55'
            ELSE '56+'
        END
)
SELECT age_group,
       revenue,
       ROUND(100.0 * revenue / SUM(revenue) OVER (), 2) AS revenue_contribution_percentage
FROM age_revenue
ORDER BY revenue DESC;
